config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  resources :ingredients, only: [:index, :new, :create]
  resources :menus, only: [:index, :new, :create, :edit, :update] do
    resources :costs, only: [:new, :create]
  end
end

app/models/amount.rb
class Amount < ApplicationRecord
  has_many :costs, dependent: :destroy
  has_many :ingredients, through: :costs
  has_many :menus, through: :costs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 0, color: '---' },
    { id: 1, color: '茶色' },
    { id: 2, color: '白色' },
    { id: 3, color: '緑色' }
  ]
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :ingredient
  belongs_to :amount
  belongs_to :menu
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :costs, dependent: :destroy
  has_many :amounts, through: :costs
  has_many :menus, through: :costs
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :menu_type
  belongs_to :color
  has_many :costs, dependent: :destroy
  has_many :ingredients, through: :costs
  has_many :amounts, through: :costs
end

app/models/menu_type.rb
class MenuType < ActiveHash::Base
  self.data = [
    { id: 0, type: '---' },
    { id: 1, type: '主菜（肉）' },
    { id: 2, type: '主菜（魚）' },
    { id: 3, type: '副菜' }
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  def new
    @cost = Cost.new
    @menu = Menu.find(params[:menu_id])
  end

  def create
    @menu = Menu.find(params[:menu_id])
    amount = Amount.where(weight_per_ten: params[:menu][:weight_per_ten]).first_or_initialize
    amount.save
    
    cost = Cost.new(menu_id: @menu.id, amount_id: amount.id, ingredient_id: params[:menu][:ingredient_id])

    if cost.save
      redirect_to new_menu_cost_path(@menu.id)
    else
      render "new"
    end
  end
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredients_path
    else
      render "new"
    end
  end
  
  private
  def ingredient_params
    params.require(:ingredient).permit(:name, :value, :weight)
  end
  
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      render "new"
    end
  end
  

  def show
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :menu_type_id, :color_id)
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costs/new.html.erb
<h1>食材との紐付け</h1>
<%= form_with model: @menu, url: menu_costs_path(@menu.id), method: :post, local: true do |f|%>
  <label>
    必要な食材
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name %>
  </label>
  <br>
  <label>
    10人分の必要量
    <%= f.text_field  :weight_per_ten %>
  </label>
  <br>
  <%= f.submit "登録" %>
<% end %>

app/views/ingredients/index.html.erb
<h1>食材一覧</h1>
<%= link_to  "食材登録", new_ingredient_path %>
<ul>
  <% @ingredients.each do |ingredient| %>
    <li>
      <%= link_to '#' do%>
        <%= ingredient.name %>
        <%= ingredient.weight %>
        <%= ingredient.value %>円
      <% end %>
    </li>
  <% end %>
</ul>

app/views/ingredients/new.html.erb
<h1>食材登録画面</h1>

<%= form_with model: @ingredient, local: true do |f| %>
  <label>
    食材名
    <%= f.text_field :name %>
  </label>
  <br>
  <label>
    単価
    <%= f.number_field :value %>円
  </label>
  <br>
  <label>
    重さ・個数など
    <%= f.text_field :weight%>
  </label>
  <br>
  <%= f.submit '登録' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenuApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to  "トップページへ", root_path %>
    <%= yield %>
  </body>
</html>

app/views/menus/edit.html.erb
<h1>メニュー編集</h1>
<%= link_to  "食材との紐付け", new_menu_cost_path(@menu.id) %>
<%= form_with model: @menu, local: true do |f|%>
  <label>
    メニュー名
    <%= f.text_field :name %>
  </label>
  <br>
  <label>
    <%= f.collection_select :menu_type_id, MenuType.all, :id, :type %>
  </label>
  <br>
  <label>
    <%= f.collection_select :color_id, Color.all, :id, :color %>
  </label>
  <br>
  <%= f.submit "登録" %>
<% end %>

<% @menu.ingredients.each do |ingredient| %>
  <%= ingredient.name %>
  <%= ingredient.weight %>
<% end %>

<% @menu.amounts.each do |amount| %>
  <%= amount.weight_per_ten%>
<% end %>

app/views/menus/index.html.erb
<h1>メニュー一覧</h1>
<%= link_to "メニュー登録", new_menu_path %>
<ul>
  <% @menus.each do |menu| %>
    <li>
      <%= link_to edit_menu_path(menu.id) do %>
        <%= menu.name %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/menus/new.html.erb
<h1>メニュー登録</h1>
<%= form_with model: @menu, local: true do |f|%>
  <label>
    メニュー名
    <%= f.text_field :name %>
  </label>
  <br>
  <label>
    <%= f.collection_select :menu_type_id, MenuType.all, :id, :type %>
  </label>
  <br>
  <label>
    <%= f.collection_select :color_id, Color.all, :id, :color %>
  </label>
  <br>
  <%= f.submit "登録" %>
<% end %>

app/views/menus/show.html.erb
<h1>Menus#show</h1>
<p>Find me in app/views/menus/show.html.erb</p>

app/views/tops/index.html.erb
<h1>トップページ</h1>
<p><%= link_to '食材管理', ingredients_path %></p>
<p><%= link_to 'メニュー管理', menus_path %></p>